/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#d8dadc',
        'tertiary-fixed': '#ffddb8',
        outline: '#777587',
        'surface-container-lowest': '#ffffff',
        secondary: '#006c49',
        'on-surface': '#191c1e',
        'surface-container-highest': '#e0e3e5',
        'surface-variant': '#e0e3e5',
        'on-background': '#191c1e',
        'secondary-fixed-dim': '#4edea3',
        'on-primary-fixed': '#0f0069',
        'on-secondary-fixed-variant': '#005236',
        'tertiary-container': '#885500',
        'on-primary-container': '#dad7ff',
        'on-error-container': '#93000a',
        'surface-bright': '#f7f9fb',
        background: '#f7f9fb',
        'secondary-fixed': '#6ffbbe',
        'surface-container-low': '#f2f4f6',
        error: '#ba1a1a',
        'on-tertiary': '#ffffff',
        'on-secondary-container': '#00714d',
        'surface-container': '#eceef0',
        'on-secondary': '#ffffff',
        'outline-variant': '#c7c4d8',
        'on-primary': '#ffffff',
        'on-tertiary-fixed': '#2a1700',
        'primary-fixed': '#e2dfff',
        'on-secondary-fixed': '#002113',
        surface: '#f7f9fb',
        tertiary: '#684000',
        'on-tertiary-fixed-variant': '#653e00',
        'primary-fixed-dim': '#c3c0ff',
        'inverse-primary': '#c3c0ff',
        'tertiary-fixed-dim': '#ffb95f',
        'secondary-container': '#6cf8bb',
        primary: '#3525cd',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
        'on-primary-fixed-variant': '#3323cc',
        'primary-container': '#4f46e5',
        'surface-tint': '#4d44e3',
        'on-error': '#ffffff',
        'surface-container-high': '#e6e8ea',
        'on-tertiary-container': '#ffd4a4',
        'error-container': '#ffdad6',
        'on-surface-variant': '#464555',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-margin': '1.25rem',
        'space-md': '1rem',
        'space-sm': '0.5rem',
        gutter: '1rem',
        'space-xl': '2.5rem',
        'space-lg': '1.5rem',
        'space-xs': '0.25rem',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['28px', { lineHeight: '34px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '14px', letterSpacing: '0.02em', fontWeight: '500' }],
        'headline-lg-mobile': ['24px', { lineHeight: '30px', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-md-mobile': ['18px', { lineHeight: '24px', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
